### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by giovanit** [handreassa/prenotami#1]
Hi dude,

I'm trying to execute your bot, but I have the error:

(.venv) root@giovaninote:/opt/prenotami# python3 __main__.py 
INFO:Timestamp: 2023-02-27 10:43:57.506223 - Required files available.
Rua Vieira da Costa
INFO:====== WebDriver manager ======
INFO:Get LATEST chromedriver version for google-chrome 110.0.5481
INFO:Driver [/root/.wdm/drivers/chromedriver/linux64/110.0.5481/chromedriver] found in cache
__main__.py:53: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(
Traceback (most recent call last):
  File "__main__.py", line 28, in <module>
    class Prenota:
  File "__main__.py", line 53, in Prenota
    driver = webdriver.Chrome(
  File "/opt/prenotami/.venv/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/opt/prenotami/.venv/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/opt/prenotami/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/prenotami/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/prenotami/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/opt/prenotami/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55eb60aa5d93 <unknown>
#1 0x55eb608742d7 <unknown>
#2 0x55eb6089cab0 <unknown>
#3 0x55eb60898a3d <unknown>
#4 0x55eb608dd4f4 <unknown>
#5 0x55eb608d4353 <unknown>
#6 0x55eb608a3e40 <unknown>
#7 0x55eb608a5038 <unknown>
#8 0x55eb60af98be <unknown>
#9 0x55eb60afd8f0 <unknown>
#10 0x55eb60addf90 <unknown>
#11 0x55eb60afeb7d <unknown>
#12 0x55eb60acf578 <unknown>
#13 0x55eb60b23348 <unknown>
#14 0x55eb60b234d6 <unknown>
#15 0x55eb60b3d341 <unknown>
#16 0x7fb71ba9d609 start_thread

**Comment by handreassa** [comment]
Hello! The code expects to find a folder (root level) called files and this folder is where you should put a pdf file to be used in the scheduling process (your home address file).
So the file tree should look like this:

prenotami/
**├── files
│   └── residencia.pdf**
├── __main__.py
├── parameters.yaml
├── README.md
└── requirements.txt

Can you please share how your folder structure looks like?

**Comment by giovanit** [comment]
Hello handreassa. I moved the prenotami directory to my home directory and got it to run. My question now is how should I declare the contents of the .env file?

**Comment by handreassa** [comment]
Awesome @giovanit. Hope you are able to schedule it!
